name: sparring_finder
description: "Sparring Finder is a mobile application that helps users find sparring partners and training locations. It provides a platform for martial artists to connect, schedule training sessions, and improve their skills together."


publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ^3.5.2


dependencies:
  flutter:
    sdk: flutter
  dotted_border: ^3.0.1
  image_cropper: ^9.1.0
  flutter_bloc: ^9.0.0
  equatable: ^2.0.7
  flutter_svg: ^2.0.15
  flutter_screenutil: ^5.9.3
  device_info_plus: ^11.1.1
  flutter_verification_code_field: ^1.0.9
  date_input_form_field: ^1.2.0
  http: ^1.3.0
  flutter_secure_storage: ^9.2.4
  jwt_decoder: ^2.0.1
  horizontal_week_calendar: ^0.0.18
  image_picker: ^1.1.2
  google_fonts: ^6.2.1
  syncfusion_flutter_sliders: ^29.2.4
  url_launcher: ^6.1.11
  smooth_page_indicator: ^1.2.1
  cached_network_image: ^3.4.1
  share_plus: ^11.0.0
  shared_preferences: ^2.5.3
  curved_navigation_bar: ^1.0.6
  marquee: ^2.3.0
  flutter_slidable: ^4.0.0
  syncfusion_flutter_calendar: ^29.2.5
  provider: ^6.1.5
  bloc: ^9.0.0
  http_parser: ^4.1.2
  mime: ^2.0.0
  intl: any
  collection: ^1.19.1


flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/sparring_finder_app_logo.png"
  min_sdk_android: 21 # android min sdk min:16, default 21

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.3

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/images/
    - assets/icons/

#  fonts:
#    - family: Sriracha
#      fonts:
#        - asset: assets/fonts/Sriracha/Sriracha-Regular.ttf
#          style: normal
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
