// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyByvy1tpDDCrtTnJlqzaRI5jyseew7vxSk',
    appId: '1:256001435980:web:5eef58c41938d0e94187e9',
    messagingSenderId: '256001435980',
    projectId: 'workshop-mds-20893',
    authDomain: 'workshop-mds-20893.firebaseapp.com',
    storageBucket: 'workshop-mds-20893.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCItT_VhLUVbebZhgV46UYR50gHdwThNqM',
    appId: '1:256001435980:android:9b506a961542ffb54187e9',
    messagingSenderId: '256001435980',
    projectId: 'workshop-mds-20893',
    storageBucket: 'workshop-mds-20893.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA6dM7IW6g4MAmw4I3R_Awg2VqZLzuVTWc',
    appId: '1:256001435980:ios:e1fd4b66b7b992024187e9',
    messagingSenderId: '256001435980',
    projectId: 'workshop-mds-20893',
    storageBucket: 'workshop-mds-20893.firebasestorage.app',
    iosBundleId: 'com.sparringfinder.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA6dM7IW6g4MAmw4I3R_Awg2VqZLzuVTWc',
    appId: '1:256001435980:ios:247cb66b67a357d74187e9',
    messagingSenderId: '256001435980',
    projectId: 'workshop-mds-20893',
    storageBucket: 'workshop-mds-20893.firebasestorage.app',
    iosBundleId: 'com.sparringFinderApp.sparringFinderApplication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyByvy1tpDDCrtTnJlqzaRI5jyseew7vxSk',
    appId: '1:256001435980:web:ead88350b5948d694187e9',
    messagingSenderId: '256001435980',
    projectId: 'workshop-mds-20893',
    authDomain: 'workshop-mds-20893.firebaseapp.com',
    storageBucket: 'workshop-mds-20893.firebasestorage.app',
  );

}